### ISSUE TITLE
Modify CLI so new inputString can be typed

### ISSUE THREAD

**Issue by Cronan** [KeenanCronyn/WordscapesCheater#18]

**Comment by KeenanCronyn** [comment]
I would run from this:

C:\Users\keenan\Desktop\Git\WordscapesCheater\src\WordscapesCheat.CLI\obj\Debug\WordscapesCheatCLI.exe

**Comment by Cronan** [comment]
Bin\Debug is better

**Comment by KeenanCronyn** [comment]
Okay, so it'll be here:

C:\Users\keenan\Desktop\Git\WordscapesCheater\src\WordscapesCheat.CLI\bin\Debug

Not sure if it matters, but any reason why?

**Comment by Cronan** [comment]
The obj folder is used to store temporary build artifacts like object files before copying to the bin folder. Bin always holds the final result. (Bin is short for binary)
