### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by Cronan** [KeenanCronyn/WordscapesCheater#6]
Needs tests

**Comment by Cronan** [comment]
https://docs.microsoft.com/en-us/visualstudio/test/getting-started-with-unit-testing?view=vs-2017

**Comment by KeenanCronyn** [comment]
When I get home I am going to focus on this. I did a bit of reading on this and understand the high level aspect of it:

1. Work out what a method should do given a correct input
2. Work out the all the different inputs that could be passed (correct and incorrect) and then the results of each input
3. Write a test that verifies each input

I'll start with the most important method and go from there.

But first I'll finish reading through this: https://docs.microsoft.com/en-us/visualstudio/test/unit-test-basics?view=vs-2017

**Comment by Cronan** [comment]
Exactly correct, and you’ll be writing tests that test the library, not the console .
